### ISSUE TITLE
Encountered conflicts

### ISSUE THREAD

**Issue by sshen23** [swat-ds/our-beloved-friend#4]
@jtruitt1 @betovargas  Finished tagging A0011517 and committed to main, but I am concerned there are some conflicts. Could you check to see if it's alright? I'll go through and edit it again if necessary. Thank you

**Comment by jtruitt1** [comment]
@sshen23 Sorry about that, I was making some changes at the same time. It was just a few find-and-replace commands, so I'll see if I can restore your version and then just run my find-and-replace again.

**Comment by jtruitt1** [comment]
@sshen23 I had to restore your first commit of A0011517_Transcript.xml, so you may have lost a little bit of tagging, but I think most of it should still be there. I'll re-implement my changes to the other files and close this.
